New

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -2,10 +2,13 @@
 # Get the process ID of the Gunicorn master process
 # Send a HUP signal to the Gunicorn master process to initiate a graceful reload
 
-kill -SIGHUP 87885
+pid=$(pgrep gunicorn)
+kill -HUP "$pid"
 sleep 5
-if ! kill -0 87885 2>/dev/null; then
-	echo "Reloading Gunicorn failed. Check the logs for more information."
+if kill -0 "$pid" >/dev/null 2>&1; then
+    echo "Gunicorn reload failed."
+    exit 1
 else
-	echo "Gunicorn reloaded successfully."
+    echo "Gunicorn reloaded successfully."
 fi
+exit 0
